%YAML:1.0
---
image_width: 1920
image_height: 1080
camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [ 1385.92, 0.0, 951.982,
          0.0, 1385.92, 534.084,
          0.0, 0.0, 1.0 ]
dist_coeffs: !!opencv-matrix
  rows: 1
  cols: 8
  dt: d
  data: [ 0.117627, -0.248549, 0.0, 0.0, 0.107441, 0.0, 0.0, 0.0 ]
distortion_model: plumb_bob
